#     $ find $(PROJ_SRC_DIR)/ -name "*.c" | grep -Ev "tests|doc" | sort | awk '{ print "\t"$1" \\" }'

include $(CLEAR_VARS)

PROJ_VERSION := 4.8.0
PROJ_SRC_DIR := proj-$(PROJ_VERSION)/src

LOCAL_MODULE    := proj
LOCAL_C_INCLUDES := $(LOCAL_PATH)/$(PROJ_SRC_DIR)
LOCAL_CFLAGS    := -DJNI_ENABLED=1 \
        -D__ANDROID__ \
        -DPROJ_LIB="\"/data/data/uk.os.oslabs.proj4/lib/\""
LOCAL_LDLIBS := -lm
LOCAL_LDLIBS += -llog
LOCAL_SRC_FILES := \
	$(PROJ_SRC_DIR)/PJ_aea.c \
	$(PROJ_SRC_DIR)/PJ_aeqd.c \
	$(PROJ_SRC_DIR)/PJ_airy.c \
	$(PROJ_SRC_DIR)/PJ_aitoff.c \
	$(PROJ_SRC_DIR)/PJ_august.c \
	$(PROJ_SRC_DIR)/PJ_bacon.c \
	$(PROJ_SRC_DIR)/PJ_bipc.c \
	$(PROJ_SRC_DIR)/PJ_boggs.c \
	$(PROJ_SRC_DIR)/PJ_bonne.c \
	$(PROJ_SRC_DIR)/PJ_cass.c \
	$(PROJ_SRC_DIR)/PJ_cc.c \
	$(PROJ_SRC_DIR)/PJ_cea.c \
	$(PROJ_SRC_DIR)/PJ_chamb.c \
	$(PROJ_SRC_DIR)/PJ_collg.c \
	$(PROJ_SRC_DIR)/PJ_crast.c \
	$(PROJ_SRC_DIR)/PJ_denoy.c \
	$(PROJ_SRC_DIR)/PJ_eck1.c \
	$(PROJ_SRC_DIR)/PJ_eck2.c \
	$(PROJ_SRC_DIR)/PJ_eck3.c \
	$(PROJ_SRC_DIR)/PJ_eck4.c \
	$(PROJ_SRC_DIR)/PJ_eck5.c \
	$(PROJ_SRC_DIR)/PJ_eqc.c \
	$(PROJ_SRC_DIR)/PJ_eqdc.c \
	$(PROJ_SRC_DIR)/PJ_fahey.c \
	$(PROJ_SRC_DIR)/PJ_fouc_s.c \
	$(PROJ_SRC_DIR)/PJ_gall.c \
	$(PROJ_SRC_DIR)/PJ_geos.c \
	$(PROJ_SRC_DIR)/PJ_gins8.c \
	$(PROJ_SRC_DIR)/PJ_gn_sinu.c \
	$(PROJ_SRC_DIR)/PJ_gnom.c \
	$(PROJ_SRC_DIR)/PJ_goode.c \
	$(PROJ_SRC_DIR)/PJ_gstmerc.c \
	$(PROJ_SRC_DIR)/PJ_hammer.c \
	$(PROJ_SRC_DIR)/PJ_hatano.c \
	$(PROJ_SRC_DIR)/PJ_healpix.c \
	$(PROJ_SRC_DIR)/PJ_igh.c \
	$(PROJ_SRC_DIR)/PJ_imw_p.c \
	$(PROJ_SRC_DIR)/PJ_isea.c \
	$(PROJ_SRC_DIR)/PJ_krovak.c \
	$(PROJ_SRC_DIR)/PJ_labrd.c \
	$(PROJ_SRC_DIR)/PJ_laea.c \
	$(PROJ_SRC_DIR)/PJ_lagrng.c \
	$(PROJ_SRC_DIR)/PJ_larr.c \
	$(PROJ_SRC_DIR)/PJ_lask.c \
	$(PROJ_SRC_DIR)/PJ_lcc.c \
	$(PROJ_SRC_DIR)/PJ_lcca.c \
	$(PROJ_SRC_DIR)/PJ_loxim.c \
	$(PROJ_SRC_DIR)/PJ_lsat.c \
	$(PROJ_SRC_DIR)/PJ_mbt_fps.c \
	$(PROJ_SRC_DIR)/PJ_mbtfpp.c \
	$(PROJ_SRC_DIR)/PJ_mbtfpq.c \
	$(PROJ_SRC_DIR)/PJ_merc.c \
	$(PROJ_SRC_DIR)/PJ_mill.c \
	$(PROJ_SRC_DIR)/PJ_mod_ster.c \
	$(PROJ_SRC_DIR)/PJ_moll.c \
	$(PROJ_SRC_DIR)/PJ_natearth.c \
	$(PROJ_SRC_DIR)/PJ_nell.c \
	$(PROJ_SRC_DIR)/PJ_nell_h.c \
	$(PROJ_SRC_DIR)/PJ_nocol.c \
	$(PROJ_SRC_DIR)/PJ_nsper.c \
	$(PROJ_SRC_DIR)/PJ_nzmg.c \
	$(PROJ_SRC_DIR)/PJ_ob_tran.c \
	$(PROJ_SRC_DIR)/PJ_ocea.c \
	$(PROJ_SRC_DIR)/PJ_oea.c \
	$(PROJ_SRC_DIR)/PJ_omerc.c \
	$(PROJ_SRC_DIR)/PJ_ortho.c \
	$(PROJ_SRC_DIR)/PJ_poly.c \
	$(PROJ_SRC_DIR)/PJ_putp2.c \
	$(PROJ_SRC_DIR)/PJ_putp3.c \
	$(PROJ_SRC_DIR)/PJ_putp4p.c \
	$(PROJ_SRC_DIR)/PJ_putp5.c \
	$(PROJ_SRC_DIR)/PJ_putp6.c \
	$(PROJ_SRC_DIR)/PJ_robin.c \
	$(PROJ_SRC_DIR)/PJ_rpoly.c \
	$(PROJ_SRC_DIR)/PJ_sconics.c \
	$(PROJ_SRC_DIR)/PJ_somerc.c \
	$(PROJ_SRC_DIR)/PJ_stere.c \
	$(PROJ_SRC_DIR)/PJ_sterea.c \
	$(PROJ_SRC_DIR)/PJ_sts.c \
	$(PROJ_SRC_DIR)/PJ_tcc.c \
	$(PROJ_SRC_DIR)/PJ_tcea.c \
	$(PROJ_SRC_DIR)/PJ_tmerc.c \
	$(PROJ_SRC_DIR)/PJ_tpeqd.c \
	$(PROJ_SRC_DIR)/PJ_urm5.c \
	$(PROJ_SRC_DIR)/PJ_urmfps.c \
	$(PROJ_SRC_DIR)/PJ_vandg.c \
	$(PROJ_SRC_DIR)/PJ_vandg2.c \
	$(PROJ_SRC_DIR)/PJ_vandg4.c \
	$(PROJ_SRC_DIR)/PJ_wag2.c \
	$(PROJ_SRC_DIR)/PJ_wag3.c \
	$(PROJ_SRC_DIR)/PJ_wag7.c \
	$(PROJ_SRC_DIR)/PJ_wink1.c \
	$(PROJ_SRC_DIR)/PJ_wink2.c \
	$(PROJ_SRC_DIR)/aasincos.c \
	$(PROJ_SRC_DIR)/adjlon.c \
	$(PROJ_SRC_DIR)/bch2bps.c \
	$(PROJ_SRC_DIR)/bchgen.c \
	$(PROJ_SRC_DIR)/biveval.c \
	$(PROJ_SRC_DIR)/dmstor.c \
	$(PROJ_SRC_DIR)/emess.c \
	$(PROJ_SRC_DIR)/gen_cheb.c \
	$(PROJ_SRC_DIR)/geocent.c \
	$(PROJ_SRC_DIR)/geod_for.c \
	$(PROJ_SRC_DIR)/geod_inv.c \
	$(PROJ_SRC_DIR)/geod_set.c \
	$(PROJ_SRC_DIR)/jniproj.c \
	$(PROJ_SRC_DIR)/mk_cheby.c \
	$(PROJ_SRC_DIR)/nad_cvt.c \
	$(PROJ_SRC_DIR)/nad_init.c \
	$(PROJ_SRC_DIR)/nad_intr.c \
	$(PROJ_SRC_DIR)/p_series.c \
	$(PROJ_SRC_DIR)/pj_apply_gridshift.c \
	$(PROJ_SRC_DIR)/pj_apply_vgridshift.c \
	$(PROJ_SRC_DIR)/pj_auth.c \
	$(PROJ_SRC_DIR)/pj_ctx.c \
	$(PROJ_SRC_DIR)/pj_datum_set.c \
	$(PROJ_SRC_DIR)/pj_datums.c \
	$(PROJ_SRC_DIR)/pj_deriv.c \
	$(PROJ_SRC_DIR)/pj_ell_set.c \
	$(PROJ_SRC_DIR)/pj_ellps.c \
	$(PROJ_SRC_DIR)/pj_errno.c \
	$(PROJ_SRC_DIR)/pj_factors.c \
	$(PROJ_SRC_DIR)/pj_fwd.c \
	$(PROJ_SRC_DIR)/pj_gauss.c \
	$(PROJ_SRC_DIR)/pj_geocent.c \
	$(PROJ_SRC_DIR)/pj_gridinfo.c \
	$(PROJ_SRC_DIR)/pj_gridlist.c \
	$(PROJ_SRC_DIR)/pj_init.c \
	$(PROJ_SRC_DIR)/pj_initcache.c \
	$(PROJ_SRC_DIR)/pj_inv.c \
	$(PROJ_SRC_DIR)/pj_latlong.c \
	$(PROJ_SRC_DIR)/pj_list.c \
	$(PROJ_SRC_DIR)/pj_log.c \
	$(PROJ_SRC_DIR)/pj_malloc.c \
	$(PROJ_SRC_DIR)/pj_mlfn.c \
	$(PROJ_SRC_DIR)/pj_msfn.c \
	$(PROJ_SRC_DIR)/pj_mutex.c \
	$(PROJ_SRC_DIR)/pj_open_lib.c \
	$(PROJ_SRC_DIR)/pj_param.c \
	$(PROJ_SRC_DIR)/pj_phi2.c \
	$(PROJ_SRC_DIR)/pj_pr_list.c \
	$(PROJ_SRC_DIR)/pj_qsfn.c \
	$(PROJ_SRC_DIR)/pj_release.c \
	$(PROJ_SRC_DIR)/pj_strerrno.c \
	$(PROJ_SRC_DIR)/pj_transform.c \
	$(PROJ_SRC_DIR)/pj_tsfn.c \
	$(PROJ_SRC_DIR)/pj_units.c \
	$(PROJ_SRC_DIR)/pj_utils.c \
	$(PROJ_SRC_DIR)/pj_zpoly1.c \
	$(PROJ_SRC_DIR)/proj.c \
	$(PROJ_SRC_DIR)/proj_etmerc.c \
	$(PROJ_SRC_DIR)/proj_mdist.c \
	$(PROJ_SRC_DIR)/proj_rouss.c \
	$(PROJ_SRC_DIR)/rtodms.c \
	$(PROJ_SRC_DIR)/vector1.c
include $(BUILD_SHARED_LIBRARY)
